Stereo processing setup through basic image streaming between smartphones
azaat/RecSync-android-arcore pull request #1
Opened 2022-04-01 11:17 UTC by azaat

2022-04-01 11:27 UTC, azaat commented
What is done here now:

- Basic image streaming with Sockets
- Matching image pairs and reporting them via ImagePairAvailable interface
- Fixed RecSync bug which led to preview lags after first recording

A more of an architectural question on this class:
[app/src/main/java/com/azaat/smstereo/StereoController.kt](https://github.com/azaat/RecSync-android/pull/1/files#diff-7554b1640b7e5a09ab38eb14c36064df09ece544af7f7a0bd6b6844d3e5b1fa7) - how to setup interaction between StereoController events and UI events in the Activity correctly? (I guess just carrying Context object everywhere is a wrong approach)

2022-04-01 11:34 UTC, azaat commented on app/src/main/java/com/azaat/smstereo/imagestreaming/ImageMatcher.kt
> +        frameInfo.displayStreamFrame(clientFrame);
This will be removed since interaction with UI should be in StereoController

2022-04-02 16:30 UTC, DmiitriyJarosh requested changes

2022-04-02 16:30 UTC, DmiitriyJarosh commented on app/src/main/java/com/azaat/smstereo/imagestreaming/BasicStreamClient.kt
> +    (private var address: InetAddress, var utils: FileTransferUtils) : StreamClient() {
strange code style

2022-04-02 16:30 UTC, DmiitriyJarosh commented on app/src/main/java/com/azaat/smstereo/imagestreaming/BasicStreamClient.kt
> +            frameProcessor.execute {
can we remove check for shutdown? maybe we can guarantee that is not shutdowned or add utils func like executeIfAlive?

2022-04-02 16:30 UTC, DmiitriyJarosh commented on app/src/main/java/com/azaat/smstereo/imagestreaming/BasicStreamClient.kt
> +                    clientSocket = Socket(address, PORT)
is socket created for each file? maybe better to have connection opened for all files fast transfer?

2022-04-02 16:30 UTC, DmiitriyJarosh commented on app/src/main/java/com/azaat/smstereo/imagestreaming/BasicStreamClient.kt
> +            if (::clientSocket.isInitialized) {
а когда мы сокет пересоздаем - прошлое соединение закрывается?

2022-04-02 16:30 UTC, DmiitriyJarosh commented on app/src/main/java/com/azaat/smstereo/imagestreaming/BasicStreamServer.kt
> +                val outputDir = Files.createDirectories(
I think output path should be provided from the constructor, not created here

2022-04-02 16:30 UTC, DmiitriyJarosh commented on app/src/main/java/com/azaat/smstereo/imagestreaming/StreamServer.kt
> +    abstract fun stopExecuting()
how we can communicate with such server?

2022-04-02 16:30 UTC, DmiitriyJarosh commented on app/src/main/java/com/azaat/smstereo/imagestreaming/StreamServer.kt
> +    abstract fun stopExecuting()
to take imgs for example

2022-04-02 16:30 UTC, DmiitriyJarosh commented on app/src/main/java/com/azaat/smstereo/imagestreaming/ImageMatcher.kt
> +        frameInfo.displayStreamFrame(clientFrame);
sounds great

2022-04-02 16:30 UTC, DmiitriyJarosh commented on app/src/main/java/com/azaat/smstereo/imagestreaming/ImageMatcher.kt
> +        if (!latestFrames.isEmpty()) {
use "if `latestFrames.isEmpty()` return" -> reduce level of nesting

2022-04-02 16:30 UTC, DmiitriyJarosh commented on app/src/main/java/com/azaat/smstereo/imagestreaming/ImageMatcher.kt
> +            val matchingTimestamp = latestFrames.stream()
what is stream? it is java stream?

2022-04-02 16:30 UTC, DmiitriyJarosh commented on app/src/main/java/com/azaat/smstereo/imagestreaming/ImageMatcher.kt
> +                .min(Comparator.comparingLong { leaderTimestamp: Long ->
why filter is necessary, just min will not work?

2022-04-02 16:30 UTC, DmiitriyJarosh commented on app/src/main/java/com/azaat/smstereo/imagestreaming/ImageMatcher.kt
> +    fun onClientImageAvailable(clientFrame: File, timeDomainConverter: SoftwareSyncBase) {
why you need file here if only its name is used?

2022-04-02 16:30 UTC, DmiitriyJarosh commented on app/src/main/java/com/azaat/smstereo/imagestreaming/ImageMatcher.kt
> +    fun onClientImageAvailable(clientFrame: File, timeDomainConverter: SoftwareSyncBase) {
also converter -> can it be different across calls?

2022-04-02 16:30 UTC, DmiitriyJarosh commented on app/src/main/java/com/azaat/smstereo/imagestreaming/ImageMatcher.kt
> +        val latestFrames = frameInfo.latestFrames
frameinfo - I think not great name for smth with latestFrames))

2022-04-02 16:30 UTC, DmiitriyJarosh commented on app/src/main/java/com/azaat/smstereo/imagestreaming/BasicStreamServer.kt
> +    private val imageMatcher: ImageMatcher = ImageMatcher(frameInfo, stereoController)
I think it should be lifted out,  and the pipeline will be: server -> imageMatcher -> consumer

2022-04-02 16:30 UTC, DmiitriyJarosh commented on app/src/main/java/com/azaat/smstereo/imagestreaming/FileTransferUtils.kt
> +class FileTransferUtils(var mContext: Context) {
Where context is used? I think it should be object, not class

2022-04-02 16:30 UTC, DmiitriyJarosh commented on app/src/main/java/com/azaat/smstereo/imagestreaming/FileTransferUtils.kt
> +            return Paths.get(filePath, fileName).toFile()
Paths.get(filePath, fileName) -> to variable

2022-04-02 16:30 UTC, DmiitriyJarosh commented on app/src/main/java/com/azaat/smstereo/depthestimation/StereoCalibration.kt
> +class StereoCalibration {
Why is it empty?

2022-04-02 16:30 UTC, DmiitriyJarosh commented on app/src/main/java/com/azaat/smstereo/depthestimation/StereoCalibration.kt
> +class StereoCalibration {
Also, better use depth.estimation, not depthestimation

2022-04-02 16:30 UTC, DmiitriyJarosh commented on app/src/main/java/com/googleresearch/capturesync/CameraActivity.java
> +public class CameraActivity extends Activity implements FrameInfo {
lets use delegates for frameinfo implementation

2022-04-02 16:30 UTC, DmiitriyJarosh commented on app/src/main/java/com/googleresearch/capturesync/CameraActivity.java
> +                () -> streamImageView.setImageBitmap(streamBitmap)
stream is based on image view? in future it will be better to use surface with rendering

2022-04-02 16:30 UTC, DmiitriyJarosh commented on app/src/main/java/com/googleresearch/capturesync/CameraActivity.java
> +                        softwareSyncLeader.getStereoController().runStereoCalibration();
here you have to provide some "view" interface to controller, but also remove it in activity onDestroy (if stereoController lives more than this activity)

2022-04-02 16:30 UTC, DmiitriyJarosh commented on app/src/main/java/com/googleresearch/capturesync/FrameInfo.java
> +    public void displayStreamFrame(File streamFrame);
looks like some god interface, describe for what is it used?

2022-04-02 16:30 UTC, DmiitriyJarosh commented on app/src/main/java/com/googleresearch/capturesync/ResultProcessor.java
> +                  context.onStreamFrame(jpgFile, syncedSensorTimestampNs);
I think for realtime processing based on files will be slow, better to continue with some ram buffers

2022-05-21 20:11 UTC, closed without merging